# Default values for podinfo.
image:
  repository: ghcr.io/stefanprodan/podinfo
  tag: 6.1.3
  pullPolicy: IfNotPresent

podAnnotations: {}

service:
  enabled: true
  type: ClusterIP
  port: 9898

gateway:
  selector: infra-pub-ingressgateway

hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 6
  cpu: 80
  memory: 512Mi

canary:
  enabled: true
  # Istio traffic policy tls can be DISABLE or ISTIO_MUTUAL
  istioTLS: DISABLE
  istioIngress:
    enabled: true
    # Istio ingress gateway name
    gateway: public-gateway.istio-system.svc.cluster.local
    # external host name eg. podinfo.example.com
    host: podinfo.example.com
  analysis:
    # schedule interval (default 60s)
    interval: 30s
    # max number of failed metric checks before rollback
    threshold: 10
    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 60
    # canary increment step
    # percentage (0-100)
    stepWeight: 30
  thresholds:
    # minimum req success rate (non 5xx responses)
    # percentage (0-100)
    successRate: 99
    # maximum req duration P99
    # milliseconds
    latency: 500
  loadtest:
    enabled: true
    # load tester address
    url: http://flagger-loadtester.istio-system/
  helmtest:
    enabled: false
    # helm tester address
    url: http://flagger-helmtester.kube-system/

resources:
  limits:
  requests:
    cpu: 100m
    memory: 32Mi

nodeSelector: {}

tolerations: []

affinity: {}

nameOverride: ""
fullnameOverride: ""

logLevel: info
backend: #http://backend-podinfo:9898/echo
backends: []
message: #UI greetings

faults:
  delay: false
  error: false

httpServer:
  timeout: 30s
