name: Enforce Label for PRs
on:
  pull_request:
    types: [labeled, opened, edited, synchronize]
jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
    - name: Check if PR has a label
      id: check-label
      uses: actions/github-script@v6
      with:
        script: |
          const requiredLabel = "approved"; // Set your required label name
          const labels = context.payload.pull_request.labels.map(label => label.name);
          if (!labels.includes(requiredLabel)) {
            core.setFailed(`PR must have the label "${requiredLabel}" to be merged.`);
          }
